### ISSUE TITLE
More links

### ISSUE THREAD

**Issue by fpoli** [viperproject/bitbucket-issue-migration#11]
Here are some examples of comments in which it would be possible to detect and convert to Github the branch name or Mercurial commit hash:

* [ ] "Although good progress was made in branch krantikiran_issue_216_bactrack_after_in, no solution that is general enough was reached yet" (Silver issue 216)
* [x] "→ <<cset 3314d13def03>>" (Silver issue 38)
* [ ] "This issue was fixed in branch fabiopakk_issue_162_assume_as_inhale" (Silver issue 162)

**Comment by marcoeilers** [comment]
Another example for a missing commit hash conversion: https://github.com/fpoli/viper-silicon/issues/359
("Resolved with commit a29dbf439162")

**Comment by fpoli** [comment]
It seems that the hash should have been recognized, so that seems a bug. Regarding the branch names I personally think that we shouldn't try to recognize and link them, because branches can be deleted.

**Comment by gauravpartha** [comment]
Another example: https://github.com/fpoli/viper-carbon/issues/187 
"Commit 55b0239 contains a temporary fix  ..."

**Comment by ArquintL** [comment]
Branches could be linked in theory:
"ntruessel/silver/default" -> https://github.com/fpoli/viper-silver/tree/ntruessel/silver/default

**Comment by ArquintL** [comment]
Wrong regex was used to detect commit hashes -> fixed in 6dad746
Branch names won't be detected / converted

**Comment by fpoli** [comment]
I reopen just to keep track of what should be checked after the migration
