### ISSUE TITLE
Manual migration steps

### ISSUE THREAD

**Issue by fpoli** [viperproject/bitbucket-issue-migration#18]
* [x] File `logfile-0208-z3.zip` of bitbucket issue viperproject/silicon/#208 is too big and cannot be uploaded as a gist file. This has to be done manually.
* [x] Manually rewrite the `.hgignore` file to `.gitignore` (see #25).
* [x] Publish the mapping of commits as a Github gist.
* [x] Check Silver warnings:
```
Prepare github issue #314 from bitbucket pull request...
Warning: could not map mercurial commit '2a53e4eba176' (source of a PR) to git.
...
Prepare github issue #390 from bitbucket pull request...
Warning: could not map mercurial commit '7b83703b96ba' (source of a PR) to git.
...
Prepare github issue #418 from bitbucket pull request...
Warning: could not map mercurial commit '544d4e703501' (source of a PR) to git.
...
Prepare github issue #434 from bitbucket pull request...
Warning: could not map mercurial commit '90b3da501740' (source of a PR) to git.
```
* [ ] Check Silicon warnings:
```
Prepare github issue #425 from bitbucket pull request...
Warning: could not map mercurial commit '2b88aa4f08ee' (source of a PR) to git.
...
Prepare github issue #460 from bitbucket pull request...
Warning: could not map mercurial commit 'a0ac36b78221' (source of a PR) to git.
...
Prepare github issue #470 from bitbucket pull request...
Warning: could not map mercurial commit '8ece9dbc0928' (source of a PR) to git.
```

**Comment by fpoli** [comment]
@ArquintL could you check what causes the Silicon/Silver warnings reported above?

**Comment by ArquintL** [comment]
> Prepare github issue #314 from bitbucket pull request...
> Warning: could not map mercurial commit '2a53e4eba176' (source of a PR) to git.

2a53e4eba176 is a mercurial commit in a fork. This commit was not pulled in, because this [PR](https://bitbucket.org/viperproject/silver/pull-requests/14) is not open but declined
@fpoli how should we handle these cases?

**Comment by fpoli** [comment]
> > Prepare github issue #314 from bitbucket pull request...
> > Warning: could not map mercurial commit '2a53e4eba176' (source of a PR) to git.
> > 2a53e4eba176 is a mercurial commit in a fork. This commit was not pulled in, because this [PR](https://bitbucket.org/viperproject/silver/pull-requests/14) is not open but declined
> > @fpoli how should we handle these cases?

Thanks for checking. I mainly wanted to be sure that the warning doesn't hide some important bug. In this case I guess we could pull branches for all PRs, independently from their status. If that's not easy then we can just ignore the warning.

**Comment by ArquintL** [comment]
The first Silicon warning results from a declined PR as well.
Adapting the pull branch logic is trivial, filtering for open PRs simply needs to be removed (in `get_fork_commits`).
Pulling the corresponding commit for merged pull requests shouldn't result in any commits being added to the repo. Pulling the commits for declined PRs should fix this issue. The only question would be whether one wants declined commits in the history or not...

**Comment by fpoli** [comment]
Deleting branches for declined PRs is easier than adding them after the
migration, so I would add them during the migration.

**Comment by ArquintL** [comment]
Fixed in a5ec5f9

**Comment by fpoli** [comment]
Output of the full migration: [migration.log](https://github.com/viperproject/bitbucket-issue-migration/files/4231504/migration.log)

**Comment by viper-admin** [comment]
The mapping of commits is here: https://gist.github.com/viper-admin/39f772e0c38ee60daae24543b2112325

**Comment by fpoli** [comment]
- [x] Only warning to check, for SIlver:
```
Prepare github issue #301 from bitbucket issue...
Prepare github issue #302 from bitbucket pull request...
Prepare github issue #303 from bitbucket pull request...
Prepare github issue #304 from bitbucket pull request...
Prepare github issue #305 from bitbucket pull request...
Prepare github issue #306 from bitbucket pull request...
Prepare github issue #307 from bitbucket pull request...
Prepare github issue #308 from bitbucket pull request...
Prepare github issue #309 from bitbucket pull request...
Prepare github issue #310 from bitbucket pull request...
Prepare github issue #311 from bitbucket pull request...
Prepare github issue #312 from bitbucket pull request...
Prepare github issue #313 from bitbucket pull request...
Prepare github issue #314 from bitbucket pull request...
Prepare github issue #315 from bitbucket pull request...
Warning: could not map mercurial commit '2a53e4eba176' (source of a PR) to git.
```

It's for a non-existing fork
