### ISSUE TITLE
Migrate participants and/or subscribe users

### ISSUE THREAD

**Issue by marcoeilers** [viperproject/bitbucket-issue-migration#22]
I created the issue https://github.com/fpoli/viper-silicon/issues/261 but I'm not marked as subscribed to it or as a participant. I assume that means that I will not be notified if something is changed or there are new comments.

Is there a way to change that and keep the people who created the issues and wrote comments updated?

**Comment by fpoli** [comment]
In the final migration the `bitbucket user meilers` will be translated as `@meilers`, so you should get notifications.

**Comment by gauravpartha** [comment]
> 
> 
> In the final migration the `bitbucket user meilers` will be translated as `@meilers`, so you should get notifications.

Users who are assigned to an issue in the bitbucket repo are currently not assigned in the github issue. Will this also be the case after the migration?

**Comment by fpoli** [comment]
> > In the final migration the `bitbucket user meilers` will be translated as `@meilers`, so you should get notifications.
> 
> Users who are assigned to an issue in the bitbucket repo are currently not assigned in the github issue. Will this also be the case after the migration?

Yes, users will also be assigned to github issues.

**Comment by gauravpartha** [comment]
I have not checked this, but will the "Bitbucket watchers" also get migrated to "Github issue participants"? Because for those there may not be a "bitbucket user ..." issue, since one can choose to watch an issue without ever doing anything with the issue.

**Comment by fpoli** [comment]
> I have not checked this, but will the "Bitbucket watchers" also get migrated to "Github issue participants"? Because for those there may not be a "bitbucket user ..." issue, since one can choose to watch an issue without ever doing anything with the issue.

Unfortunately the list of watchers seems to be private, even for viperproject team members...  The [Bitbucket's API](https://developer.atlassian.com/bitbucket/api/2/reference/resource/) seem to only tell you whether the _current user_ is watching the issue or not.
