### ISSUE TITLE
User references are scrambled

### ISSUE THREAD

**Issue by marcoeilers** [viperproject/bitbucket-issue-migration#23]
In issue https://github.com/fpoli/viper-silicon/issues/367, in the "Nicolaj just closed..." comment by Malte, "@Federico Poli" was tagged in the original comment (https://bitbucket.org/viperproject/silicon/issues/367/incompleteness-with-non-linear-arithmetic), but in the Github version, you see the string "{557058:2a067556-b105-4ce3-b3ec-bf9ecac58455}" instead.

**Comment by fpoli** [comment]
Uh, thanks! We need to map even Bitbucket user UUIDs in the `config.USER_MAPPING` dict.
