### ISSUE TITLE
Tags are missing

### ISSUE THREAD

**Issue by aterga** [viperproject/bitbucket-issue-migration#24]
The released versions of Silver ([74329a5](https://github.com/fpoli/viper-silver/commit/74329a578c93c7fff3bf9fdd1c3d9751e7dad55e)), Silicon ([88f1d34](https://github.com/fpoli/viper-silicon/commit/88f1d340c3cc88efd8e15bc11733df97c071b6e2)), Carbon ([ba027f2](https://github.com/fpoli/viper-carbon/commit/ba027f2b3f32139d44ea680eb96eb1a47791c010)), and ViperServer ([7cc7ce5](https://github.com/fpoli/viper-viperserver/commit/7cc7ce5224a723ab1fcdbe2e7ea0cbfbd727fcab)) should be tagged. This should be easy to add manually as we only had one release so far. I think we should add these tags once the migration is over. 

However, other tags are also missing, e.g., in Silicon. Not sure what's the simplest way, maybe also adding them manually.

**Comment by fpoli** [comment]
Good point, thanks! I think it's easier to do this manually, because the existing script to migrate from Mercurial doesn't convert tags.

**Comment by ArquintL** [comment]
I see a git tag in my local git silver repo after performing the migration (using `git tag`). Is this somehow just not published or does GitHub use a different tagging feature?

**Comment by fpoli** [comment]
Good catch, the command to upload the git tags is missing.

**Comment by fpoli** [comment]
It should be fixed now.
