### ISSUE TITLE
changes in issues not visible

### ISSUE THREAD

**Issue by gauravpartha** [viperproject/bitbucket-issue-migration#26]
In https://bitbucket.org/viperproject/carbon/issues/270/incomplete-behaviour-when-using-gotos-to#comment-51802030 one sees the bullet points showing what actions were taken by the users. In this case  "changed title to Incomplete behaviour when using gotos to jump out of loops" and "edited description". In the Github issue, this is not the case: https://github.com/fpoli/viper-carbon/issues/270#issuecomment-583463321

I think this can be helpful and it would be nice to get this information if it's easily possible.

**Comment by fpoli** [comment]
I'll add a generic "edited description" and "edited content" message.
