### ISSUE TITLE
Selection of the master branch

### ISSUE THREAD

**Issue by fpoli** [viperproject/bitbucket-issue-migration#30]
See the FIXME at
https://github.com/viperproject/bitbucket-issue-migration/blob/5f7695e6088af785aef3516691043d82cea0ac4a/import-forks.py#L142

**Comment by fpoli** [comment]
This problem does not cause exceptions; it just selects the wrong commit to be the HEAD of the master branch on GitHub. It's something easy to fix manually after the migration, in case this happens.

**Comment by fabiopakk** [comment]
Actually, the filter works correctly in the sense of selecting the heads with "default" label (referring to the default branch). However, Mercurial accepts having multiple heads, temporarily, until "hg merge" is issued to merge them. While Git prevents having multiple heads by either merging them at once (for example in "git pull" or "git merge <branch>") or rejecting the command completely. So there's no mapping from a Mercurial repository to a Git repository if there are multiple heads in default branch.
That however can be easily fix by issuing a "hg merge" command and restarting the script. I've added such instructions to the script while reporting the exception.
