### ISSUE TITLE
Pull request exceptions on private repositories

### ISSUE THREAD

**Issue by fabiopakk** [viperproject/bitbucket-issue-migration#36]
Pull requests aren't being properly handled by the script, causing the following exception:

github.GithubException.GithubException: 422 {"errors": [{"field": "head", "code": "invalid", "resource": "PullRequest"}], "message": "Validation Failed", "documentation_url": "https://developer.github.com/v3/pulls/#create-a-pull-request"}

Investigation must be done. The GitHub account status for 'viperproject' is 'Team', therefore the feature is supported.

**Comment by fpoli** [comment]
What is the BitBucket pull request being migrated?

**Comment by fabiopakk** [comment]
It is the only PR available in "tutorial" repository, which can be found in this link: https://bitbucket.org/viperproject/tutorial/pull-requests/

**Comment by fpoli** [comment]
I would add a `print(..)` to see what is the value of the `head` field of the request that creates the pull request in GitHub. I would then check that the `head` is a valid branch name in the migrated git repository.

**Comment by fabiopakk** [comment]
Issue fixed together with #35. Already committed to master branch.
