### ISSUE TITLE
Linking

### ISSUE THREAD

**Issue by fpoli** [viperproject/bitbucket-issue-migration#4]
- [x] links to issues
- [x] links to commits
    - [x] it might be useful to build an independent tool that given two repositories (mercurial and git) builds a mapping of the commits
- [x] links to PRs
- [x] links to issues of other repositories (e.g. given a full url)
- [x] links to commits of other repositories

Less important:
- [x] links to users

**Comment by ArquintL** [comment]
Bitbucket uses the following linking style:
- link an issue: "issue #number"
- link a PR: "pull request #number"
(source: https://confluence.atlassian.com/bitbucket/mark-up-comments-305037452.html)

**Comment by fpoli** [comment]
I'm using this library for creating the issues: https://pygithub.readthedocs.io/en/latest/reference.html

**Comment by ArquintL** [comment]
Bitbucket URLs to issues get currently properly converted if they occur in an issue or a comment of an issue.
`Silicon issue #261` does not get converted, although it follows Bitbucket's linking style, for three reasons:
1. Bitbucket ignores `Silicon` and interprets it as link to issue #261 (in the current repo)
2. GitHub equally interpret it (without performing any changes)
3. `Silicon issue #261` could be a markdown link text (as in issue #153), in which case no transformation would be desirable

**Comment by ArquintL** [comment]
On GitHub, PRs are also issues. Therefore, links to issues in PRs and comments of PRs get already handled

**Comment by ArquintL** [comment]
PR #8 contains the first set of features

**Comment by fpoli** [comment]
BItbucket allows mentioning users as `@{557058:50339889-65da-459d-811e-7532e71d77f6}`

(UUID of that user: `adb2b557-3f78-435b-93c8-f551587ccb59`)

**Comment by fpoli** [comment]
As part of the dry run we can collect all UUIDs and account IDs of the users, to put them in the `config.USER_MAPPING` dictionary

**Comment by ArquintL** [comment]
All found user mentions (incl. account ids and uuids) are collected and printed by the linking script

**Comment by ArquintL** [comment]
The conversion of plain text issue references has to be discussed:
e.g. "Silicon issue #5" => (how) should this be converted? If not converted, GitHub will interpret `#5` itself

**Comment by ArquintL** [comment]
Replace "issue #5" by an explicit github url to issue 5 of the same repo (except it occurs in a Markdown link `[...]()`
Do the same (but with adding an offset) for "pull request #5"

**Comment by ArquintL** [comment]
For commit hashes: check prefixes with 7 or more chars

**Comment by ArquintL** [comment]
> Replace "issue #5" by an explicit github url to issue 5 of the same repo (except it occurs in a Markdown link `[...]()`
> Do the same (but with adding an offset) for "pull request #5"

The following case-insensitive regex is used to detect issues not appearing in Markdown links:
`\[.*?\]|(silicon |silver |carbon )?issue #(\d+)/i`

However, silver does not contain issues, PRs, or comments that satisfy the right term of the disjunction

see 012aa7352c4fd52ddc1eed9a465861e977e56030

**Comment by ArquintL** [comment]
Commit hashes and explicit links to commits are now converted as well. However, a commit hash appearing in squared brackets in a Markdown link is left untouched, which results in the underlying link being correctly updated but the link label remaining the old hg hash

**Comment by fpoli** [comment]
Some cases that I found. I'm not saying we have to handle them, but I list them here to remember that they exist.

* "Although good progress was made in branch [krantikiran\_issue\_216\_bactrack\_after\_in](https://bitbucket.org/viperproject/silver/branch/krantikiran_issue_216_bactrack_after_in), no solution that is general enough was reached yet" (Silver issue 216)
* "→ <<cset 3314d13def03>>" (Silver issue 38)
* "This issue was fixed in branch fabiopakk_issue_162_assume_as_inhale" (Silver issue 162)

**Comment by fpoli** [comment]
I'll open a new issue for those cases
