### ISSUE TITLE
Script is getting stuck when porting some repositories

### ISSUE THREAD

**Issue by fabiopakk** [viperproject/bitbucket-issue-migration#40]
For some reason the script is getting stuck while porting the following repositories:

- Deprecated / silicon-assertable
- Deprecated / silver-assertable
- Deprecated / silver-coarse
- Fork / silicon-coarse
- Fork / silicon-verifiedif
- Fork / silver-attributes
- Fork / silver-verifiedif

This seems to be related with the process of fetching forks of the repository to create local branches. More investigation is needed.

**Comment by fpoli** [comment]
For Silicon and Carbon we had to manually close malformed pull requests on Bitbucket: open pull requests on Bitbucket whose source branch is private or has been deleted.

**Comment by fabiopakk** [comment]
@fpoli , I've found one such case in a private repository. The PR was already merged. What do you suggest to do with it, please?

**Comment by fpoli** [comment]
If a PR is merged then the script is not supposed to fetch the fork. Do you have a stacktrace? What's the link to the private PR?

**Comment by fabiopakk** [comment]
There's no stack trace. The scripts get stuck in this line:

` pull -r 6905b40a7517 https://hg@bitbucket.org/viperproject/<repo>`

**Comment by fabiopakk** [comment]
This issue was due to lack of HTTPS authentication. I've fixed this issue and committed the code in master brach.
