### ISSUE TITLE
Script is crashing on more complex repositories

### ISSUE THREAD

**Issue by fabiopakk** [viperproject/bitbucket-issue-migration#41]
For a variety of reasons, the script it crashing in the following repositories:

- Deprecated / rust2viper
- Deprecated / obligations/silver

The root cause must be investigated and fixed. Those two repositories must be ported as a result.

**Comment by fpoli** [comment]
What is the output?

**Comment by fabiopakk** [comment]
This issue was also fixed in fabiopakk_issues_40_and_42_stuck_and_crash, as the root cause is the same of issues #40 and #42.
