### ISSUE TITLE
Gists are created as public even for private repositories

### ISSUE THREAD

**Issue by ianhinder** [viperproject/bitbucket-issue-migration#45]
When attachments are migrated from BitBucket to GitHub, they are created as gists if they are small enough.  However, even for private repositories, the gists are public.  I was able to create secret gists as follows:
```diff
diff --git a/src/github.py b/src/github.py
index c0e87f3..bc97bcb 100644
--- a/src/github.py
+++ b/src/github.py
@@ -58,7 +58,7 @@ class GithubImport:
         gist = self.get_gist_by_description(gist_data["description"])
         if gist is None:
             gist = self.github.get_user().create_gist(
-                True,
+                False,
                 gist_data["files"],
                 gist_data["description"]
             )
```
and it seemed to work.  I wondered if it would make sense to make public gists for public repos, and secret gists for private repos, but in the end decided that they should always probably be secret.  Secret doesn't mean private; you can still access them if you know the URL, they are just not discoverable.  And if the repo is made private in future, you probably want the gists to be secret at that point.  So it's probably OK just to change True to False there, without any check on the public/private status of the repo.

**Comment by fpoli** [comment]
That's a nice idea, thank you!
