### ISSUE TITLE
Slow the script down

### ISSUE THREAD

**Issue by jasonbraganza** [viperproject/bitbucket-issue-migration#50]
Hello, 
I have been tasked with moving my orgs repos from bitbucket to github.

And your script has been a godsend!
I’ve moved most of my small repos to Github flawlessly

I seem to be hitting all sorts of rate limits with my large repos that have 600+ prs.
i cannot seem to delete the PRs, over there at bitbucket and github does not seem to want them at the rate the script wants to migrate them here

Is there any way I could ask the script to slow down?

and THANK YOU so, so, so much for making this!

**Comment by fpoli** [comment]
We are not actively maintaining this project, but it should be quite easy to add `sleep(..)` at various points. For example, before each `GET` request
https://github.com/viperproject/bitbucket-issue-migration/blob/ac8af5526ee096e04950a5d87242086197cbdf7e/src/utils.py#L4-L10
and to the various methods that interact with Github:
https://github.com/viperproject/bitbucket-issue-migration/blob/ac8af5526ee096e04950a5d87242086197cbdf7e/src/github.py#L10

You can also try increasing the delay between retries:
https://github.com/viperproject/bitbucket-issue-migration/blob/ac8af5526ee096e04950a5d87242086197cbdf7e/src/bitbucket.py#L26-L32
https://github.com/viperproject/bitbucket-issue-migration/blob/ac8af5526ee096e04950a5d87242086197cbdf7e/src/github.py#L15-L21

**Comment by jasonbraganza** [comment]
i was trying that too, mosly just before the commit lines in github.py but being a beginner i thought i was doing it dumbly 😂 

thank you for pointing out the actual places I could put them in (befor the gets) 😄 

thank you so much once again :)
